name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main
    tags:
      - '!*'

permissions:
  id-token: write # needed for AWS role assumption
  contents: write

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{ steps.set-vars.outputs.APP_NAME }}
      AWS_REGION: ${{ steps.set-vars.outputs.AWS_REGION }}
      HCP_TERRAFORM_ORG: ${{ steps.set-vars.outputs.HCP_TERRAFORM_ORG }}
      HCP_TERRAFORM_PROJECT: ${{ steps.set-vars.outputs.HCP_TERRAFORM_PROJECT }}
      HCP_TERRAFORM_WORKSPACE: ${{ steps.set-vars.outputs.HCP_TERRAFORM_WORKSPACE }}
      DISCORD_PUBLIC_KEY: ${{ steps.set-vars.outputs.DISCORD_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Load config
        id: set-vars
        # Config stored in repository root config.env
        run: |
          set -a
          source ./config.env
          set +a

          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "HCP_TERRAFORM_ORG=$HCP_TERRAFORM_ORG" >> $GITHUB_OUTPUT
          echo "HCP_TERRAFORM_PROJECT=$HCP_TERRAFORM_PROJECT" >> $GITHUB_OUTPUT
          echo "HCP_TERRAFORM_WORKSPACE=$HCP_TERRAFORM_WORKSPACE_DEV" >> $GITHUB_OUTPUT
          echo "DISCORD_PUBLIC_KEY=$DISCORD_PUBLIC_KEY_DEV" >> $GITHUB_OUTPUT

  deploy:
    needs: read-config
    uses: ./.github/workflows/workflow-deploy.yml
    with:
      app_name: ${{ needs.read-config.outputs.APP_NAME }}
      aws_region: ${{ needs.read-config.outputs.AWS_REGION }}
      hcp_terraform_org: ${{ needs.read-config.outputs.HCP_TERRAFORM_ORG }}
      hcp_terraform_project: ${{ needs.read-config.outputs.HCP_TERRAFORM_PROJECT }}
      hcp_terraform_workspace: ${{ needs.read-config.outputs.HCP_TERRAFORM_WORKSPACE }}
      discord_public_key: ${{ needs.read-config.outputs.DISCORD_PUBLIC_KEY }}
      deployment_env: 'dev'
      artifact_s3_bucket: 'enpicie-dev-lambda-artifacts'
    secrets: inherit
